#!/usr/bin/env zsh
#===============================================================================
# agent.zsh — Agent Shell bootstrap script
#===============================================================================
# Usage: source agent.zsh
# Embeds Agent functionality into the current zsh session.
#
# Dependencies:
#   - jq (JSON processing)
#   - bun (runs agsh CLI)
#===============================================================================

# ─── Environment loading ───────────────────────────────────────────────────
#
# Priority (high → low):
#   Environment variables > .agshrc > ~/.agshrc > .env > defaults
#
# .env is simple key=value, parsed line-by-line with fill-gap semantics:
# only sets a variable if it isn't already in the environment. This lets
# the user's environment variables and agshrc overrides take precedence.
# .agshrc is sourced as-is — authors are responsible for respecting priority.
#
export AGENT_ROOT="${AGENT_ROOT:-${0:A:h}}"

# Layer 1 — .env: fill gaps only
if [[ -f "$AGENT_ROOT/.env" ]]; then
  while IFS='=' read -r key value; do
    [[ -z "$key" || "$key" == \#* ]] && continue
    key="${key%%[[:space:]]*}"
    : ${(P)key:="$value"}
    export "$key"
  done < "$AGENT_ROOT/.env"
fi

# Layer 2 — defaults: fill gaps only
: ${AGENT_EXEC_DELAY:=2}
: ${AGENT_OUTPUT_MAX_LENGTH:=10000}
: ${AGENT_DEBUG:=false}
: ${AGENT_POLL_INTERVAL:=0.05}
: ${AGENT_NODES_PATH:=".agsh/nodes"}

# Layer 3 — user config
[[ -f ~/.agshrc ]] && source ~/.agshrc

# Layer 4 — project config (sourced last, overrides user)
[[ -f .agshrc ]] && source .agshrc

# Resolve AGENT_NODES_PATH to absolute
[[ "$AGENT_NODES_PATH" != /* ]] && AGENT_NODES_PATH="$PWD/$AGENT_NODES_PATH"
export AGENT_NODES_PATH

# ─── Idempotency guard ──────────────────────────────────────────────────────
[[ -n "${_AGENT_SOURCED:-}" ]] && { _agent_debug_log "[agent] already sourced"; return 1; }
_AGENT_SOURCED=1

# ─── Build CLI (once at startup, ensures dist/ is current) ─────────────────────
_build_cli() {
  command -v bun >/dev/null 2>&1 || { echo "[agent] WARNING: bun not found, CLI will not work" >&2; return 1; }
  bun build "$AGENT_ROOT/src/cli.ts" --outdir "$AGENT_ROOT/dist" --target=bun 1>/dev/null || {
    echo "[agent] WARNING: bun build failed, CLI may be stale" >&2
    return 1
  }
  # Verify the output file was created
  [[ -f "$AGENT_ROOT/dist/cli.js" ]] || {
    echo "[agent] WARNING: dist/cli.js not generated by bun build" >&2
    return 1
  }
}
_build_cli
# ─── Quick-Node Creation ───────────────────────────────────────────────────────

# ─── CLI ready check ───────────────────────────────────────────────────────────────
_agent_cli_ready() {
  [[ -f "$AGENT_ROOT/dist/cli.js" ]] || {
    echo "[agent] ERROR: dist/cli.js not found — CLI not built. Run: bun build src/cli.ts --outdir dist --target=bun" >&2
    return 1
  }
  return 0
}
# prompt: one-line semantic context node creation
# Usage: prompt <id> <content> [parent]
# Example: prompt security-audit "You are a security audit expert"
prompt() {
  local id="$1"
  local content="$2"
  local parent="${3:-root}"
  if [[ $# -lt 2 ]]; then
    echo "usage: prompt <id> <content> [parent]" >&2
    echo "  Creates a prompt node under nodes/<id>/" >&2
    return 1
  fi
  mkdir -p "$AGENT_NODES_PATH/$id"
  echo "$content" > "$AGENT_NODES_PATH/$id/context"
  echo "$parent" > "$AGENT_NODES_PATH/$id/parent"
  echo "[prompt] created node '${1}' -> nodes/${1}/" >&2
}
export -f prompt >/dev/null 2>&1 || true

agent() {
  case "${1:-help}" in
    help|--help|-h)
      echo "agent-shell - 终端原生 AI Agent"
      echo ""
      echo "Commands:"
      echo "  prompt <id> <content> [parent]  创建提示词节点"
      echo "  credential claim <id>           申领凭证，启动 agent（支持随时切换）"
      echo "  credential drop                 释放凭证，退出 agent"
      echo "  agent help                      显示此帮助"
      echo "  agent unload                     卸载 agent-shell，恢复原始 shell"
      echo "  agent debug tail                 查看调试日志 (tail -f)"
      echo "  agent debug cat                  查看调试日志 (cat)"
      echo ""
      echo "Keybindings:"
      echo "  Ctrl+G  暂停/恢复 agent"
      echo "  Ctrl+T  重试上次 API 请求"
      echo ""
      echo "Env:"
      echo "  AGENT_API_KEY       (required)  API key"
      echo "  AGENT_BASE_URL      DeepSeek API endpoint"
      echo "  AGENT_MODEL         Model name"
      echo "  AGENT_EXEC_DELAY=2  Seconds before auto-executing commands"
      ;;
    unload)
      _agent_unload
      ;;
    response)
        if [[ -n "${CREDENTIAL:-}" ]]; then
          local _hist="$AGENT_NODES_PATH/$CREDENTIAL/history"
          [[ -f "$_hist" ]] && tail -1 "$_hist" | jq -r '.[-1].content // empty' 2>/dev/null
        fi
        ;;
    debug)
      case "${2:-}" in
        tail) [[ -n "${_AGENT_DEBUG_LOG:-}" ]] && tail -f "$_AGENT_DEBUG_LOG" || echo "[agent] debug log not active (set AGENT_DEBUG=true)" >&2 ;;
        cat)  [[ -n "${_AGENT_DEBUG_LOG:-}" && -f "$_AGENT_DEBUG_LOG" ]] && cat "$_AGENT_DEBUG_LOG" || echo "[agent] debug log not found (set AGENT_DEBUG=true)" >&2 ;;
        *)    echo "agent debug tail  — follow debug log" >&2; echo "agent debug cat   — print debug log" >&2 ;;
      esac
      ;;

    *)
      echo "agent: unknown command '$1'. Try 'agent help'." >&2
      return 1
      ;;
  esac
}
export -f agent >/dev/null 2>&1 || true

# ═══════════════════════════════════════════════════════════════════
# PIPELINE STATE INITIALIZATION
#   Agent state machine: _AGENT_LOCKED, _AGENT_ARTIFACT_DIR, _AGENT_PENDING_CMD
#   P3: AGENT_STATUS_ICON
#   General: AGENT_FIFO_STATE, AGENT_SAVED_PROMPT, AGENT_FIFO_FD, etc.
# ═══════════════════════════════════════════════════════════════════

# Agent cycle lock — non-empty = agent is working, precmd should skip
_AGENT_LOCKED=""               # "0" = unlocked , "1" = locked
_AGENT_ARTIFACT_DIR=""        # non-empty = pending command capture directory
_AGENT_PENDING_CMD=""         # the command buffered for user acceptance

# Async agent state
AGENT_FIFO_STATE=""
AGENT_FIFO_FD=""
AGENT_API_PID=""
_AGENT_EXEC_TOOL_ID=""    # Tool call ID for pending exec
_AGENT_IN_TMUX=""     # "1" when running inside tmux
_AGENT_DEBUG_LOG=""               # trace/debug log path
_AGENT_CAPTURE=""               # flag: agent-initiated command in accept-line pipeline
_AGENT_CAPTURE_CRED_BEFORE=""   # credential snapshot for drop scenario
AGENT_STATUS_ICON='◇'      # [P3] Status icon default

# ─── Tmux detection ──────────────────────────────────────────────────────────
# Auto-exec requires tmux; warn if running outside it.
if [[ -n "${TMUX:-}" && -n "${TMUX_PANE:-}" ]] && command -v tmux >/dev/null 2>&1; then
  _AGENT_IN_TMUX="1"
else
  echo "[agent] WARNING: agent-shell auto-exec requires tmux. Running outside tmux will disable automatic command execution." >&2
fi


_agent_last_speed=""
_agent_last_reasoning=""

# ═══════════════════════════════════════════════════════════════════
# PIPELINE 1: [node] Prompt Prefix
# State: PROMPT, CREDENTIAL, _AGENT_BASE_PROMPT, promptsubst
# CREDENTIAL controls whether [node] prefix appears in the prompt.
# ═══════════════════════════════════════════════════════════════════

# ─── Credential State ─────────────────────────────────────────────────────────────────
CREDENTIAL=""
AGENT_PAUSED=""

# ─── Prerequisite Check ─────────────────────────────────────────────────────────────
# fail-fast: errors on missing deps and blocks source
_agent_check_deps() {
  local missing=()
  command -v bun >/dev/null 2>&1 || missing+=("bun (https://bun.sh)")
  command -v jq >/dev/null 2>&1 || missing+=("jq (brew install jq)")

  if [[ ${#missing} -gt 0 ]]; then
    echo "[agent] missing dependencies:" >&2
    for m in "${missing[@]}"; do
      echo "  - $m" >&2
    done
    return 1
  fi

  if [[ -z "${AGENT_API_KEY:-}" ]]; then
    echo "[agent] warning: AGENT_API_KEY not set. Set it before credential claim." >&2
    echo "  export AGENT_API_KEY=sk-..." >&2
  fi
  return 0
}

_agent_check_deps || return 1

# ─── Persistent Infrastructure ─────────────────────────────────────────────────
_agent_init_infra() {
  mkdir -p .agsh/tmp 2>/dev/null
  _AGENT_POLL_FIFO=".agsh/tmp/agent_poll_fifo_$$"
  rm -f "$_AGENT_POLL_FIFO" 2>/dev/null
  mkfifo "$_AGENT_POLL_FIFO" 2>/dev/null || return 1
  exec {_AGENT_POLL_FD}<>"$_AGENT_POLL_FIFO"
  zle -F "$_AGENT_POLL_FD" _agent_poll_handler

  # --- State FIFO ---
  AGENT_FIFO_STATE=".agsh/tmp/agent_fifo_$$_state"
  rm -f "$AGENT_FIFO_STATE" 2>/dev/null
  mkfifo "$AGENT_FIFO_STATE" 2>/dev/null || return 1
  exec {AGENT_FIFO_FD}<>"$AGENT_FIFO_STATE"
  zle -F -w "$AGENT_FIFO_FD" _agent_async_handler
  setopt no_notify no_monitor
  { while true; do sleep "${AGENT_POLL_INTERVAL:-0.1}"; echo x > "$_AGENT_POLL_FIFO"; done } &
  _AGENT_POLL_PID=$!
  ### [P3] Default status icon (inactive)
  AGENT_STATUS_ICON='◇'

  # Auto-create root node if missing (first-run convenience)
  if [[ ! -d "$AGENT_NODES_PATH/root" ]]; then
    _agent_cli_ready && bun run "$AGENT_ROOT/dist/cli.js" init 2>/dev/null
  fi
}


# ─── Credential Validation ─────────────────────────────────────────────────────────────────

# ═══════════════════════════════════════════════════════════════════
# PLUGIN LIFECYCLE
# ═══════════════════════════════════════════════════════════════════
_AGENT_LOADED_PLUGINS=()

_agent_parse_plugin_segment() {
  local file="$1" mode="$2"
  [[ -f "$file" ]] || { echo "[agent] plugin file not found: $file" >&2; return 1; }
  grep -q "^# @register" "$file" || { echo "[agent] plugin error: missing # @register in $file" >&2; return 1; }
  grep -q "^# @unregister" "$file" || { echo "[agent] plugin error: missing # @unregister in $file" >&2; return 1; }
  case "$mode" in
    register) sed -n "/^# @register/,/^# @unregister/{/^# @register/d;/^# @unregister/d;p;}" "$file" ;;
    unregister) sed -n "/^# @unregister/,\$p" "$file" | grep -v "^# @unregister" ;;
  esac
}

_agent_source_plugin_segment() {
  local file="$1" mode="$2" segment
  segment="$(_agent_parse_plugin_segment "$file" "$mode")" || return 1
  [[ -z "$segment" ]] && return 0
  mkdir -p .agsh/tmp 2>/dev/null
  local tmpfile=".agsh/tmp/agsh_plugin_$$.zsh"
  printf "%s\n" "$segment" > "$tmpfile"
  if ! source "$tmpfile"; then
    echo "[agent] plugin $mode error in $file" >&2
    rm -f "$tmpfile"
    return 1
  fi
  rm -f "$tmpfile"
  return 0
}

_agent_get_plugin_chain() {
  local cred="$1"
  _agent_cli_ready || return 1
  bun run "$AGENT_ROOT/dist/cli.js" prefix-chain --cred "$cred" --type plugin --paths 2>/dev/null
}

_agent_source_plugin_chain() {
  local cred="$1" paths p
  paths="$(_agent_get_plugin_chain "$cred" 2>/dev/null)" || return 0
  [[ -z "$paths" ]] && return 0
  while IFS= read -r p; do
    [[ -z "$p" ]] && continue
    _agent_source_plugin_segment "$p" register && _AGENT_LOADED_PLUGINS+=("$p")
  done <<< "$paths"
}

_agent_unload_plugin_chain() {
  if (( ${#_AGENT_LOADED_PLUGINS} == 0 )); then return 0; fi
  local i
  for (( i = ${#_AGENT_LOADED_PLUGINS}; i > 0; i-- )); do
    _agent_source_plugin_segment "${_AGENT_LOADED_PLUGINS[i]}" unregister
  done
  _AGENT_LOADED_PLUGINS=()
}

_agent_switch_plugins() {
  local old="$1" new="$2" old_paths new_paths p
  old_paths="$(_agent_get_plugin_chain "$old" 2>/dev/null)" || old_paths=""
  new_paths="$(_agent_get_plugin_chain "$new" 2>/dev/null)" || new_paths=""

  local old_only=()
  while IFS= read -r p; do
    [[ -z "$p" ]] && continue
    if ! echo "$new_paths" | grep -qF "$p" 2>/dev/null; then
      old_only+=("$p")
    fi
  done <<< "$old_paths"

  local new_only=()
  while IFS= read -r p; do
    [[ -z "$p" ]] && continue
    if ! echo "$old_paths" | grep -qF "$p" 2>/dev/null; then
      new_only+=("$p")
    fi
  done <<< "$new_paths"

  local i
  for (( i = ${#old_only}; i > 0; i-- )); do
    _agent_source_plugin_segment "${old_only[i]}" unregister
  done
  # Rebuild loaded list: keep common + add new-only
  local new_loaded=()
  while IFS= read -r p; do
    [[ -z "$p" ]] && continue
    new_loaded+=("$p")
  done <<< "$new_paths"
  _AGENT_LOADED_PLUGINS=("${new_loaded[@]}")

  for p in "${new_only[@]}"; do
    [[ -z "$p" ]] && continue
    _agent_source_plugin_segment "$p" register && _AGENT_LOADED_PLUGINS+=("$p")
  done
}


# _validate_credential: Delegates to TypeScript CLI for 4-layer validation.
_validate_credential() {
  bun run "$AGENT_ROOT/dist/cli.js" credential validate "$1"
}


# ─── Credential Shell Command ────────────────────────────────────────────────────
# credential(): Standard shell function — works in scripts, pipes, and interactively.
# Sets/unset CREDENTIAL env var; agent lifecycle managed by precmd hook.
#
# Usage: credential claim <id> — export CREDENTIAL=<id>, start agent via precmd
#       credential drop        — unset CREDENTIAL, stop agent via precmd
#       credential help        — show help
credential() {
  local sub="${1:-help}"
  case "$sub" in
    claim)
      local id="${2:-}"
      if [[ -z "$id" ]]; then
        echo "Usage: credential claim <id>" >&2
        return 1
      fi
      _validate_credential "$id" || return 1
      local old="${CREDENTIAL:-}"
      # Remove old lock first
      if [[ -n "$old" && "$old" != "$id" ]]; then
        rm -f "$AGENT_NODES_PATH/$old/.lock"
      fi
      # Set CREDENTIAL before loading plugins (so @register sees correct cred)
      export CREDENTIAL="$id"
      echo $$ > "$AGENT_NODES_PATH/$id/.lock"
      # Load/switch plugins with CREDENTIAL already set
      if [[ -n "$old" && "$old" != "$id" ]]; then
        _agent_switch_plugins "$old" "$id"
        echo "[credential] CREDENTIAL set to: ${CREDENTIAL}" >&2
      elif [[ -z "$old" ]]; then
        _agent_source_plugin_chain "$id"
        echo "[credential] CREDENTIAL set to: ${CREDENTIAL}" >&2
      fi
      ;;
    drop)
      _agent_unload_plugin_chain
      [[ -n "$CREDENTIAL" ]] && rm -f "$AGENT_NODES_PATH/$CREDENTIAL/.lock"
      CREDENTIAL=""
      echo "[credential] CREDENTIAL cleared" >&2
      ;;
    help|--help|-h)
      echo "Usage:" >&2
      echo "  credential claim <id>   — 申领凭证，自动加载插件并启动 agent" >&2
      echo "  credential drop         — unset CREDENTIAL env, stop agent" >&2
      echo "  credential help         — show this help" >&2
      echo "  credential               — show this help" >&2
      echo "" >&2
      echo "Or set CREDENTIAL directly: export CREDENTIAL=<id>" >&2
      ;;
    *)
      echo "credential: unknown subcommand: $sub" >&2
      echo "Usage: credential {claim|drop|help}" >&2
      return 1
      ;;
  esac
}

# ─── Keybinding Handlers ───────────────────────────────────────────────────────────────
# toggle-pause: Ctrl+G toggle pause/resume
_toggle_pause() {
  if [[ -z "$CREDENTIAL" ]]; then
    # Not in agent loop — ignore
    return 0
  fi
  
  if [[ -n "$AGENT_PAUSED" ]]; then
    # Resume — restart the agent cycle
    AGENT_PAUSED=""
    _agent_wake
    echo "[agent] Resumed" >&2
  else
    # Pause
    AGENT_PAUSED="1"
    ### [P3] Pause icon
    AGENT_STATUS_ICON='●'
    AGENT_STATUS_INFO=''
    # Also cancel any pending exec
    [[ -n "$_AGENT_PENDING_CMD" ]] && {
        _AGENT_PENDING_CMD=""
        _AGENT_EXEC_TOOL_ID=""
        _agent_clear_timeout
        POSTDISPLAY=""
        _agent_render
    }
    echo "[agent] Paused (Ctrl+G to resume)" >&2
  fi
  
  return 0
}

# retry-api: Ctrl+T retry last API request with current CONTEXT
_retry_api() {
  if [[ -z "$CREDENTIAL" ]]; then
    return 0
  fi
  # Kill stuck API process if running, let precmd start fresh cycle
  if [[ -n "${AGENT_API_PID:-}" ]] && kill -0 "$AGENT_API_PID" 2>/dev/null; then
    _agent_debug_log "[agent] Killing stuck API ($AGENT_API_PID)..."
    kill "$AGENT_API_PID" 2>/dev/null
    AGENT_API_PID=""
    _agent_unlock
  fi
  if [[ -n "${_AGENT_PENDING_CMD:-}" ]]; then
    return 0
  fi
  _agent_debug_log "[agent] Retrying API request..."
  _agent_wake
}

# ═══════════════════════════════════════════════════════════════════
# PIPELINE 2: Command Execution Rendering
# State: BUFFER, POSTDISPLAY, _AGENT_EXEC_TOOL_ID
# Widgets: _agent_accept_line
# ═══════════════════════════════════════════════════════════════════

# ─── Bridge: Single Rendering Entry Point ──────────────────────────────────────
# ALL pipelines set state (PROMPT, BUFFER, POSTDISPLAY, RPROMPT, AGENT_STATUS_*).
# Central prompt rendering. Also triggered by accept-line exec path → precmd pipeline.
# Cached prompt has CREDENTIAL pre-expanded, %# left literal for zsh to expand.
_agent_render() {
  local _saved="$PROMPT"
  PROMPT="${_AGENT_CACHED_PROMPT:-$PROMPT}"
  zle reset-prompt
  PROMPT="$_saved"
}

# _agent_render_sync: synchronous display flush (zle -R wrapper)
# Used in accept-line exec path to force immediate screen updates during eval.
_agent_render_sync() {
  zle -R
}


# ─── Suggestion Apply Widgets ───────────────────────────────────────────────
# _agent_apply_suggestion: copy the pending agent command into the edit buffer
# and clear the pending state. Safe to call from a widget context.
_agent_apply_suggestion() {
    if [[ -n "${_AGENT_PENDING_CMD:-}" && -z "$BUFFER" ]]; then
        BUFFER="$_AGENT_PENDING_CMD"
        CURSOR=${#BUFFER}
        _AGENT_PENDING_CMD=""
        POSTDISPLAY=""
        _agent_clear_timeout
        _agent_render
    fi
}

# _agent_render_suggestion: display pending agent suggestion as POSTDISPLAY
# Used by async_handler and zle-line-init to show the pending command.
_agent_render_suggestion() {
    if [[ -n "${_AGENT_PENDING_CMD:-}" && -z "$POSTDISPLAY" && -z "$BUFFER" ]]; then
        POSTDISPLAY="$_AGENT_PENDING_CMD"
        zle -R
    fi
}


# _agent_accept_suggestion_tab: Tab accepts the suggestion when one is pending;
# otherwise falls back to the default Tab behavior (completion/menu).
_agent_accept_suggestion_tab() {
    if [[ -n "${_AGENT_PENDING_CMD:-}" && -z "$BUFFER" ]]; then
        _agent_apply_suggestion
    else
        zle expand-or-complete
    fi
}

# _agent_accept_suggestion_forward: Right Arrow accepts the suggestion when one is
# pending; otherwise falls back to the default Right Arrow behavior.
_agent_accept_suggestion_forward() {
    if [[ -n "${_AGENT_PENDING_CMD:-}" && -z "$BUFFER" ]]; then
        _agent_apply_suggestion
    else
        zle forward-char
    fi
}


# _agent_zle_line_init: ZLE startup widget that renders a pending agent suggestion
# as POSTDISPLAY. Runs each time the line editor starts (prompt displayed).
_agent_zle_line_init() {
    _agent_render_suggestion
}



# ─── ZLE Widget ───────────────────────────────────────────────────────────────
# _agent_accept_line: Handles exec mode acceptance/cancellation, chat routing, pass-through
# Replaces default accept-line via zle -N accept-line.
_agent_accept_line() {
    local buf="$BUFFER"

    # Grey phase: user pressed Enter while POSTDISPLAY is shown, do nothing
    if [[ -z "$buf" && -n "${_AGENT_PENDING_CMD:-}" ]]; then
        return
    fi

    # User typed their own command during grey window: cancel pending state
    if [[ -n "$buf" && -n "${_AGENT_PENDING_CMD:-}" ]]; then
        _agent_clear_timeout
        POSTDISPLAY=""
        _AGENT_PENDING_CMD=""
        _AGENT_EXEC_TOOL_ID=""
        [[ -n "${_AGENT_ARTIFACT_DIR:-}" ]] && rm -rf "$_AGENT_ARTIFACT_DIR"
        _AGENT_ARTIFACT_DIR=""
        # fall through to execute BUFFER
    fi

    # Tool call: BUFFER was populated by timeout_handler, execute with capture
    if [[ -n "$buf" && -n "${_AGENT_EXEC_TOOL_ID:-}" ]]; then
        _AGENT_CAPTURE=1
        _AGENT_CAPTURE_CRED_BEFORE="${CREDENTIAL:-}"
        zle .accept-line
        return
    fi

    zle .accept-line
}



# ─── Register Widgets and Keybindings ─────────────────────────────────────────────────────
# Create the zle widget
zle -N toggle-pause _toggle_pause
zle -N retry-api _retry_api
zle -N accept-line _agent_accept_line
zle -N zle-line-init _agent_zle_line_init

# Bind keys

# Ctrl+G -> toggle-pause
bindkey '^G' toggle-pause

# Ctrl+T -> retry-api
bindkey '^T' retry-api

# Tab -> accept suggestion or expand-or-complete
bindkey '\t' _agent_accept_suggestion_tab

# Right Arrow -> accept suggestion or forward-char
bindkey '^[[C' _agent_accept_suggestion_forward

zle -N _agent_timeout_handler
zle -N _agent_async_handler
zle -N _agent_accept_suggestion_tab
zle -N _agent_accept_suggestion_forward


# ─── Export New Functions ─────────────────────────────────────────────────────────────
export -f _validate_credential credential \
         _toggle_pause _retry_api >/dev/null 2>&1 || true
export -f _agent_async_handler _agent_reset_cycle >/dev/null 2>&1 || true

# ─── Agent Cycle Lock ────────────────────────────────────────────────────────
# _agent_lock: Prevent precmd from starting new cycles while agent is working.
_agent_lock() { _AGENT_LOCKED="1"; }
# _agent_unlock: Allow precmd to start next cycle.
_agent_unlock() { _AGENT_LOCKED=""; }

# ─── Debug Log ─────────────────────────────────────────────────────────
# _agent_debug_log: append timestamped message to debug log.
# Only writes when AGENT_DEBUG is true. Safe to call unconditionally.
_agent_debug_log() {
  [[ "$AGENT_DEBUG" != "true" ]] && return
  [[ -z "${_AGENT_DEBUG_LOG:-}" ]] && _AGENT_DEBUG_LOG="${TMPDIR:-.agsh/tmp}/agent_debug_${CREDENTIAL:-global}.log"
  printf '[%s] %s\n' "$(date '+%H:%M:%S')" "$*" >> "$_AGENT_DEBUG_LOG"
}

# ─── Wake Helper ───────────────────────────────────────────────────────────
# Triggers precmd via accept-line when BUFFER is empty. Safe to call from
# zle -F handlers and keybinding widgets without interfering with user input.
_agent_wake() {
    [[ -z "$BUFFER" ]] && zle accept-line
}

_agent_preexec() {
    if [[ -n "${_AGENT_CAPTURE:-}" ]]; then
        exec 3>&1 4>&2
        exec > >(tee "$_AGENT_ARTIFACT_DIR/output") 2>&1
        _agent_start_exec_timeout
    fi
}
preexec_functions+=(_agent_preexec)



# ─── precmd Hook ───────────────────────────────────────────────────────────
# precmd IS the agent loop. Each prompt cycle checks state and drives progress.
_agent_precmd() {
    local _cmd_exit=$?      # MUST be first — capture exit code before any command runs
    _AGENT_CACHED_PROMPT='%F{cyan}[${CREDENTIAL:-none}]%f '"${_AGENT_BASE_PROMPT}"

    # ── Collect output from agent-initiated accept-line command ──
    if [[ -n "${_AGENT_CAPTURE:-}" ]]; then
        exec >&3 2>&4
        exec 3>&- 4>&-

        # Kill exec timeout watcher; alive = cmd finished, dead = timeout fired
        local _timed_out=0
        if [[ -n "${_AGENT_EXEC_TIMEOUT_PID:-}" ]]; then
            kill "$_AGENT_EXEC_TIMEOUT_PID" 2>/dev/null
            _timed_out=$(( $? != 0 ? 1 : 0 ))
            _AGENT_EXEC_TIMEOUT_PID=""
        fi
        local _capfile="$_AGENT_ARTIFACT_DIR/output"
        local _output="$(cat "$_capfile" 2>/dev/null)"
        local _tid="${_AGENT_EXEC_TOOL_ID:-}"
        local _cred_before="${_AGENT_CAPTURE_CRED_BEFORE:-}"

        [[ -n "${AGENT_OUTPUT_MAX_LENGTH:-}" && ${#_output} -gt $AGENT_OUTPUT_MAX_LENGTH ]] && \
            _output="${_output:0:$AGENT_OUTPUT_MAX_LENGTH}[truncated]"

        local _msg
        if (( _timed_out )); then
            _msg="Timed out after ${AGENT_EXEC_TIMEOUT:-?}s"
            [[ -n "$_output" ]] && _msg="${_msg}
Partial output:
$_output"
        else
            _msg="Exit code: $_cmd_exit"
            [[ -n "$_output" ]] && _msg="Exit code: $_cmd_exit
Output:
$_output"
        fi

        _record_tool_result "$_tid" "$_msg" "${_cred_before:-}"

        _AGENT_CAPTURE=""
        _AGENT_CAPTURE_CRED_BEFORE=""
        [[ -n "${_AGENT_ARTIFACT_DIR:-}" ]] && rm -rf "$_AGENT_ARTIFACT_DIR"
        _AGENT_ARTIFACT_DIR=""
        _AGENT_EXEC_TOOL_ID=""
    fi

    AGENT_STATUS_ICON='◇'; AGENT_STATUS_INFO=''

    if [[ -n "$AGENT_PAUSED" ]]; then
        AGENT_STATUS_ICON='●'
        AGENT_IN_PRECMD=0; return
    fi

    if [[ -z "$_AGENT_LOCKED" && -z "${_AGENT_PENDING_CMD:-}" ]]; then
        if [[ -n "${CREDENTIAL:-}" ]]; then
            local next_tool="$(_detect_next_pending_tool)"
            if [[ -n "$next_tool" && "$next_tool" != "null" ]]; then
                local tool_id="$(printf '%s' "$next_tool" | jq -r '.id')"
                local cmd="$(printf '%s' "$next_tool" | jq -r '.function.arguments | fromjson | .cmd' 2>/dev/null)"
                local func_name="$(printf '%s' "$next_tool" | jq -r '.function.name')"

                if [[ "$func_name" != "shell" ]]; then
                    _record_tool_result "$tool_id" "Error: unknown tool: $func_name"
                elif [[ -z "$cmd" ]]; then
                    _record_tool_result "$tool_id" "Error: no cmd in shell tool arguments"
                else
                    _AGENT_ARTIFACT_DIR="$(mktemp -d)"
                    _AGENT_PENDING_CMD="$cmd"
                    _AGENT_EXEC_TOOL_ID="$tool_id"
                    _agent_start_timeout
                fi
            else
                AGENT_STATUS_ICON='◌'; AGENT_STATUS_INFO="${_agent_last_reasoning:-0}r ${_agent_last_speed:-0}t/s"
                _agent_lock
                _start_api_call
            fi
        fi
    fi

    AGENT_IN_PRECMD=0
}
precmd_functions+=(_agent_precmd)

# ─── History-based Tool Detection ────────────────────────────────────────────────
# _detect_next_pending_tool: Scan history JSONL for assistant tool_calls
# that have no corresponding tool result message.
_detect_next_pending_tool() {
  _agent_cli_ready || { echo ""; return; }
  bun run "$AGENT_ROOT/dist/cli.js" context detect-pending --cred "$CREDENTIAL" 2>/dev/null
}



# ─── API Call Launcher ────────────────────────────────────────────────────────────
# _start_api_call: Run bun cli.js stream in background, pipe SSE events to state FIFO.
# SSE events: token→streaming, content_done→accumulate, tool_calls→accumulate, done→api_done(with data), error→error.
# TS stream reads history directly via buildContext().
_start_api_call() {
  _agent_cli_ready || { return 1; }

  # History is the authoritative source — TS stream reads it directly
  [[ "$AGENT_DEBUG" == "true" ]] && _agent_debug_log "start_api_call: cred=$CREDENTIAL"
  {
    bun run "$AGENT_ROOT/dist/cli.js" stream --cred "$CREDENTIAL" --nodes-path "$AGENT_NODES_PATH" 2>/dev/null | \
    while IFS= read -r line; do
      [[ "$line" =~ ^data:\ (.*) ]] || continue
      local event="${match[1]}"
      local etype
      etype="$(printf '%s' "$event" | jq -r '.type' 2>/dev/null)"

      case "$etype" in
        progress|token)
          local tokens speed reasoning
          read -r tokens speed reasoning < <(printf '%s' "$event" | jq -r '[(.tokens // .estimatedTokens // 0), (.speed // 0), (.reasoning // .completionTokens // 0)] | @tsv' 2>/dev/null)
          printf '{"state":"streaming","tokens":%s,"speed":%s,"reasoning":%s}\n' "$tokens" "$speed" "$reasoning"
          ;;

        content_done)
          _accumulated_content="$(printf '%s' "$event" | jq -r '.content // ""')"
          ;;

        done)
          # TS already wrote history + reasoning_file; just relay compact state to FIFO
          printf '%s' "$event" | jq -c '{state:"api_done",tokens:0} + .'
          ;;

        error)
          printf '{"state":"error","tokens":0}\n'
          ;;

        fatal)
          local errmsg
          errmsg="$(printf '%s' "$event" | jq -r '.error // "internal error"')"
          printf '{"state":"fatal","tokens":0,"message":"%s"}\n' "$errmsg"
          ;;
      esac
    done >&$AGENT_FIFO_FD
  } &
  AGENT_API_PID=$!
}

# ─── Auto-Exec Timeout ───────────────────────────────────────────────────────────
# Uses a temp FIFO + zle -F to trigger auto-exec after AGENT_EXEC_DELAY seconds.
_agent_start_timeout() {
  _agent_clear_timeout
  mkdir -p .agsh/tmp 2>/dev/null
  local _tf=".agsh/tmp/agent_timeout_fifo_$$"
  rm -f "$_tf" 2>/dev/null
  mkfifo "$_tf" 2>/dev/null || return
  exec {_AGENT_TIMEOUT_FD}<>"$_tf"
  zle -F -w "$_AGENT_TIMEOUT_FD" _agent_timeout_handler
  ( sleep "${AGENT_EXEC_DELAY:-2}"; echo x > "$_tf" ) &
  _AGENT_TIMEOUT_PID=$!
}

_agent_clear_timeout() {
  [[ -n "${_AGENT_TIMEOUT_FD:-}" ]] && zle -F "${_AGENT_TIMEOUT_FD}" 2>/dev/null
  [[ -n "${_AGENT_TIMEOUT_FD:-}" ]] && exec {_AGENT_TIMEOUT_FD}<&- 2>/dev/null
  [[ -n "${_AGENT_TIMEOUT_PID:-}" ]] && kill "$_AGENT_TIMEOUT_PID" 2>/dev/null
  _AGENT_TIMEOUT_PID=""
  rm -f ".agsh/tmp/agent_timeout_fifo_$$" 2>/dev/null
}

_agent_timeout_handler() {
  local _
  read -r _ <&$_AGENT_TIMEOUT_FD 2>/dev/null
  _agent_clear_timeout

  if [[ -n "${AGENT_PAUSED:-}" ]]; then
    return
  fi

  if [[ -n "$BUFFER" && -n "${_AGENT_PENDING_CMD:-}" ]]; then
    # User typed during the grey window: cancel the pending agent command.
    _AGENT_PENDING_CMD=""
    _AGENT_EXEC_TOOL_ID=""
    POSTDISPLAY=""
    _agent_render
    return
  fi

  if [[ -z "$BUFFER" && -n "${_AGENT_PENDING_CMD:-}" ]]; then
    # Apply pending command (tool call or agent response). Move it into BUFFER,
    # clear POSTDISPLAY, then inject Enter via tmux. _agent_accept_line
    # routes execution based on _AGENT_EXEC_TOOL_ID.
    BUFFER="$_AGENT_PENDING_CMD"
    CURSOR=${#BUFFER}
    _AGENT_PENDING_CMD=""
    POSTDISPLAY=""
    _agent_render

    if [[ -n "${_AGENT_IN_TMUX:-}" ]]; then
      ( sleep 0.1; tmux send-keys -t "$TMUX_PANE" Enter ) &
    else
      # No tmux: clear pending state so the prompt is clean.
      _AGENT_PENDING_CMD=""
      _AGENT_EXEC_TOOL_ID=""
      _agent_render
    fi
  fi
}

# ─── Execution Timeout ──────────────────────────────────────────────────────────
# Uses tmux send-keys C-c to cancel long-running captured commands.
# Mirrors the POSTDISPLAY timeout (FIFO + zle -F) structure: start/clear pair.
_agent_start_exec_timeout() {
    _agent_clear_exec_timeout
    (( ${AGENT_EXEC_TIMEOUT:-0} > 0 )) || return
    [[ -n "${_AGENT_IN_TMUX:-}" ]] || return
    ( sleep "$AGENT_EXEC_TIMEOUT"; tmux send-keys -t "$TMUX_PANE" C-c ) &
    _AGENT_EXEC_TIMEOUT_PID=$!
}

_agent_clear_exec_timeout() {
    [[ -n "${_AGENT_EXEC_TIMEOUT_PID:-}" ]] && kill "$_AGENT_EXEC_TIMEOUT_PID" 2>/dev/null
    _AGENT_EXEC_TIMEOUT_PID=""
}


# ─── zle -F Event Handler ────────────────────────────────────────────────────────
# _agent_async_handler: zle -F callback invoked when background API writes to state FIFO
# Reads JSON state line from FIFO, updates RPROMPT/POSTDISPLAY accordingly
#
# Usage: (called by zle -F automatically)
_agent_async_handler() {
  local state
  AGENT_IN_HANDLER=1
  if ! read -r state <&$AGENT_FIFO_FD 2>/dev/null; then
    # API process exited or FIFO closed unexpectedly.
    # Clean up FIFOs, unregister zle-F, refresh display.
    _agent_reset_cycle
    AGENT_IN_HANDLER=0
    return
  fi

  # Guard: skip empty reads (defensive against FIFO/zle-F edge cases)
  # Empty reads happen when zle -F spuriously fires after zle reset-prompt
  # during content display. Skip silently to prevent empty-state spin loops.
  if [[ -z "$state" ]]; then
    AGENT_IN_HANDLER=0
    return
  fi
  local s tokens content speed reasoning message
  read -r s tokens speed reasoning message < <(jq -r '[.state // "unknown", .tokens // 0, .speed // 0, .reasoning // 0, .message // ""] | @tsv' <<< "$state" 2>/dev/null)
  [[ -n "$reasoning" && "$reasoning" != "0" ]] && _agent_last_reasoning="$reasoning"

  # DEBUG: log every state the handler processes
  [[ "$AGENT_DEBUG" == "true" ]] && _agent_debug_log "HANDLER state=$s tokens=$tokens reasoning=$reasoning"

  case "$s" in
    streaming)
      # Token count updates in real-time via RPROMPT only.
      # Content streams token-by-token; full content written to history by content_done.
      local _r="${reasoning:-${_agent_last_reasoning:-0}}"
      local _s="${speed:-${_agent_last_speed:-0}}"
      ### [P3] Agent status icon
      AGENT_STATUS_ICON='◌'; AGENT_STATUS_INFO="${_r}r ${_s}t/s"
      ;;


    error)
      ### [P2] Clear buffer/exec mode
      ### [P3] Agent status icon (error)
      BUFFER=""; POSTDISPLAY=""
      AGENT_STATUS_ICON='✗'; AGENT_STATUS_INFO="${_agent_last_reasoning:-0}r ${_agent_last_speed:-0}t/s"
      _agent_unlock
      ;;

    fatal)
      ### Internal error (e.g., prefix chain topology corruption)
      AGENT_API_PID=""
      BUFFER=""; POSTDISPLAY=""
      _agent_clear_timeout
      _agent_clear_exec_timeout
      AGENT_STATUS_ICON='⚠'; AGENT_STATUS_INFO="${message:-internal error}"
      _agent_unlock
      ;;

    api_done)
      AGENT_API_PID=""

      # History already written by TS stream command.
      # Nothing else needed — history IS the context for the next cycle.
      local _content _has_tc
      _content="$(jq -r '.content // ""' <<< "$state")"
      _has_tc="$(jq -r '.tool_calls != null' <<< "$state")"

      # POSTDISPLAY: content -> "agent response", tool-only -> first tool cmd
      if [[ -z "$AGENT_PAUSED" ]]; then
        if [[ -n "$_content" ]]; then
          _AGENT_PENDING_CMD="agent response"
          _AGENT_EXEC_TOOL_ID=""
        elif [[ "$_has_tc" == "true" ]]; then
          local _tool_id _cmd _func_name
          _tool_id="$(jq -r '.tool_calls[0].id // empty' <<< "$state")"
          _cmd="$(jq -r '.tool_calls[0].function.arguments | fromjson | .cmd // empty' <<< "$state")"
          _func_name="$(jq -r '.tool_calls[0].function.name // empty' <<< "$state")"

          if [[ "$_func_name" != "shell" ]]; then
            _record_tool_result "$_tool_id" "Error: unknown tool: $_func_name"
          elif [[ -z "$_cmd" ]]; then
            _record_tool_result "$_tool_id" "Error: no cmd in shell tool arguments"
          else
            _AGENT_ARTIFACT_DIR="$(mktemp -d)"
            _AGENT_PENDING_CMD="$_cmd"
            _AGENT_EXEC_TOOL_ID="$_tool_id"
          fi
        fi
        _agent_unlock
        AGENT_STATUS_ICON='◀'; AGENT_STATUS_INFO="${_agent_last_reasoning:-0}r ${_agent_last_speed:-0}t/s"
        _agent_start_timeout
        _agent_render_suggestion
      fi
      ;;

  esac
  AGENT_IN_HANDLER=0
}

# ═══════════════════════════════════════════════════════════════════
# PIPELINE 3: Poll Handler — ensures RPROMPT stays synced
# ═══════════════════════════════════════════════════════════════════

# ─── Poll Handler ────────────────────────────────────────────────────────────────
_agent_poll_handler() {
  local _p
  read -r _p <&$_AGENT_POLL_FD 2>/dev/null || return
  [[ "${AGENT_IN_HANDLER:-0}" == "1" ]] && return
  if [[ -z "${CREDENTIAL:-}" ]]; then
    AGENT_STATUS_ICON='◇'
  ### [P3] Reset icon when no credential
  fi
  _agent_render
}

# _agent_reset_cycle: Kill old API process and clear per-cycle state.
# Does NOT touch infrastructure (FIFO, fd, handler). Safe to call anytime.
_agent_reset_cycle() {
  [[ -n "${AGENT_API_PID:-}" ]] && kill -0 "$AGENT_API_PID" 2>/dev/null && kill "$AGENT_API_PID" 2>/dev/null
  AGENT_API_PID=""
  _agent_clear_timeout
  _agent_clear_exec_timeout
  _agent_unlock
  _AGENT_EXEC_TOOL_ID=""
  _agent_last_speed=""
  _agent_last_reasoning=""
}

# ─── Agent Main Loop ───────────────────────────────────────────────────────────────

# _record_tool_result: Writes a tool result directly to history JSONL.
# History is the ONLY authoritative data source; no shell context caching.
# Usage: _record_tool_result <tool_call_id> <content> [credential]
_record_tool_result() {
  local _cred="${3:-${CREDENTIAL:-}}"
  [[ -z "$_cred" ]] && return
  _agent_cli_ready || return
  mkdir -p .agsh/tmp 2>/dev/null
  local _content_file=".agsh/tmp/agent_tool_$$.txt"
  printf '%s' "$2" > "$_content_file"
  bun run "$AGENT_ROOT/dist/cli.js" context record-tool \
    --cred "$_cred" \
    --nodes-path "$AGENT_NODES_PATH" \
    --id "$1" \
    --content-file "$_content_file" >/dev/null 2>/dev/null
  rm -f "$_content_file"
}

# ═══════════════════════════════════════════════════════════════════
# PIPELINE 1+3: Prompt Rendering
# P1: PROMPT with [node] prefix via ${CREDENTIAL:-none}
# P3: RPROMPT with agent status (AGENT_STATUS_ICON + AGENT_STATUS_INFO)
# ═══════════════════════════════════════════════════════════════════

# ─── Prompt Enhancement ──────────────────────────────────────────────────────
# Embed credential prefix into PROMPT via promptsubst.
# Each time the prompt renders, ${CREDENTIAL:-none} expands to the
# current credential id (or "none"), shown in cyan before the user's prompt.
# No precmd hook needed — promptsubst handles everything.
_AGENT_BASE_PROMPT="${PROMPT:-%# }"
setopt promptsubst 2>/dev/null
PROMPT='%F{cyan}[${CREDENTIAL:-none}]%f '"${_AGENT_BASE_PROMPT}"
_AGENT_CACHED_PROMPT='%F{cyan}[${CREDENTIAL:-none}]%f '"${_AGENT_BASE_PROMPT}"
RPROMPT='${AGENT_STATUS_ICON:-} ${AGENT_STATUS_INFO:-}'


# --- startup banner -----------------------------------------------------------
_agent_banner() {
  local v
  v="$(bun run "$AGENT_ROOT/dist/cli.js" --version 2>/dev/null)" || v="dev"
  echo "agent-shell ${v}"
  echo "  prompt     - 创建提示词节点"
  echo "  credential - 申领/释放凭证"
  echo "  Ctrl+G     - 暂停/恢复"
  echo "  Ctrl+T     - 重试 API"
  echo "  输入 agent help 查看完整命令"
  echo "  agent unload - 卸载 agent-shell"
  echo ""
}

_agent_unload() {
  # 1. Kill API background process if running
  if [[ -n "${AGENT_API_PID:-}" ]] && kill -0 "$AGENT_API_PID" 2>/dev/null; then
    kill "$AGENT_API_PID" 2>/dev/null
  fi
  _agent_clear_exec_timeout

  # 2. Cleanup async infrastructure
  zle -F "${AGENT_FIFO_FD:-}" 2>/dev/null
  [[ -n "${AGENT_FIFO_FD:-}" ]] && exec {AGENT_FIFO_FD}<&- 2>/dev/null
  rm -f "${AGENT_FIFO_STATE:-}" 2>/dev/null

  # 3. Remove ZLE widgets
  zle -D toggle-pause 2>/dev/null
  zle -D retry-api 2>/dev/null

  # 4. Restore keybindings to zsh defaults
  zle -D accept-line 2>/dev/null
  bindkey -r '^G' 2>/dev/null
  bindkey -r '^T' 2>/dev/null

  ### [P1] Restore PROMPT to pre-agent state
  # 5. Restore original prompt (if we have it)
  if [[ -n "${_AGENT_BASE_PROMPT:-}" ]]; then
    PROMPT="$_AGENT_BASE_PROMPT"
  fi
  ### [P3] Clear RPROMPT + status icon
  RPROMPT=""
  AGENT_STATUS_ICON=''
  AGENT_STATUS_INFO=''
  ### [P2] Clear POSTDISPLAY
  POSTDISPLAY=""

  # 6. Remove precmd hooks
  local new_precmd=()
  for fn in "${precmd_functions[@]}"; do
    [[ "$fn" == "_agent_precmd" ]] && continue
    new_precmd+=("$fn")
  done
  precmd_functions=("${new_precmd[@]}")

  # 7. Remove agent preexec hook
  local _new_hooks=()
  for _fn in "${preexec_functions[@]}"; do
    [[ "$_fn" == "_agent_preexec" ]] && continue
    _new_hooks+=("$_fn")
  done
  preexec_functions=("${_new_hooks[@]}")

  # 8. Remove lock files
  local lock_files=("$AGENT_NODES_PATH/"*/.lock(N))
  [[ ${#lock_files} -gt 0 ]] && rm -f "${lock_files[@]}"



  # 9. Unset all agent variables
  unset AGENT_FIFO_STATE AGENT_API_PID
  unset AGENT_FIFO_FD AGENT_PAUSED CREDENTIAL
  unset _agent_last_speed _agent_last_reasoning _AGENT_BASE_PROMPT _AGENT_CACHED_PROMPT
  unset _AGENT_EXEC_TOOL_ID _AGENT_LOCKED _AGENT_ARTIFACT_DIR _AGENT_PENDING_CMD _AGENT_CAPTURE _AGENT_CAPTURE_CRED_BEFORE _AGENT_IN_TMUX
  unset _AGENT_SOURCED

  # 10. Unfunction agent commands
  unfunction prompt 2>/dev/null
  unfunction agent 2>/dev/null
  unfunction _agent_async_handler 2>/dev/null
  unfunction _agent_reset_cycle 2>/dev/null
  unfunction credential 2>/dev/null
  unfunction _toggle_pause 2>/dev/null
  unfunction _retry_api 2>/dev/null
  unfunction _agent_accept_line 2>/dev/null
  unfunction _agent_unload 2>/dev/null
  unfunction _start_api_call 2>/dev/null
  unfunction _agent_wake 2>/dev/null
  unfunction _agent_preexec 2>/dev/null

  # Clean up polling timer
  zle -F "${_AGENT_POLL_FD:-}" 2>/dev/null
  [[ -n "${_AGENT_POLL_FD:-}" ]] && exec {_AGENT_POLL_FD}<&- 2>/dev/null
  [[ -n "${_AGENT_POLL_PID:-}" ]] && kill "$_AGENT_POLL_PID" 2>/dev/null
  rm -f "${_AGENT_POLL_FIFO:-}" 2>/dev/null

  _agent_debug_log "[agent] unloaded"
  [[ -f "${_AGENT_DEBUG_LOG:-}" ]] && rm -f "$_AGENT_DEBUG_LOG" 2>/dev/null
}
_agent_banner
_agent_init_infra
# ─── Export Cycle Functions ─────────────────────────────────────────────────────────────
export -f _record_tool_result >/dev/null 2>&1 || true
